### PR TITLE
[Feature] Excel spreadsheet generation module

### PR DESCRIPTION
**Pull request by sujaypatil96**
This PR seeks to address issue #110.

The work on this PR will be done in the following stages:

- [x] Commit for setting up skeleton of the Excel sheet generator module
- [x] Commit for identifying the various high level methods that will need to into the `ExcelGenerator` class
- [x] Commits for implementing various internal and utility methods that will be called by the high level methods in the class alongside implementing the high level method itself

> TODO: Further breakdown each of the checklist into major changes made as and when they are implemented.

To test the functionality being implemented in this PR:

```
$ gen-excel examples/organization.yaml --filename "test"
```

Follow appropriate syntax for CLI on Windows and Bash.

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Note: This [commit](https://github.com/linkml/linkml/pull/302/commits/2507304a57c3c871b8ae9ac006a7c65426102440) now ensures that all sheet names are created per the classes and each of the sheets are appropriately associated with the right slot or column names.

**Comment by sujaypatil96** [comment]
@cmungall: Even with the current `visit_slot()` method, I am able to see some parent slot names associated with existing slot names. For example with the `examples/organization.yaml` schema, there's a slot, `first name` which has an `is_a` relationship with another slot, `name` and I am able to capture it in `visit_slot`. So as I understand the problem, you'd like to a `name` column alongside other slot names, for the respective worksheets?

The current output looks like: [test.xlsx](https://github.com/linkml/linkml/files/7080288/test.xlsx)

Essentially, we would like to see a `name` column in the `Employee` worksheet? Am I understanding this correctly?

**Comment by sujaypatil96** [comment]
I'll add a test for this feature, like you recorded on this [comment](https://github.com/linkml/linkml/pull/302#pullrequestreview-739914371), on a separate PR.

It looks like the feature works as expected when you run the following command:

```
$ gen-excel examples/organization.yaml
```

Input LinkML schema: [organization.yaml](https://github.com/linkml/linkml/blob/main/examples/organization.yaml)
Result xlsx file: [excelgen_0.0.1.xlsx](https://github.com/linkml/linkml/files/7124842/excelgen_0.0.1.xlsx)

**Comment by sujaypatil96** [comment]
@cmungall: I've added `unittest` test cases to test the `ExcelGenerator` generator module. It looks like the tests run fine, I can add a few failure test later too. The ones I've added now are only the success cases.

The PR is ready for review and merge.

**Comment by sujaypatil96** [comment]
@cmungall: The output Excel spreadsheet option has been fixed.

Now, you can provide the output filename like:

```
$ gen-excel examples/organization.yaml --output ~/Desktop/organization.xlsx
```

Or if you choose not to provide an output filename, the program will create a file with the filename `organization_excelgen_0.0.1`, in this case.

I think the PR is ready to be merged.

**Review by cmungall — APPROVED** [review]

**Pull request merged**
