### PR TITLE
Remove @vocab from enums in JSON LD contexts

### PR DESCRIPTION
**Pull request by vincentkelleher**
This fixes the issue mentioned in #2122 😊 

I've also worked on the `Deprecation` class tests which were depending on the `linkml` package version meaning they would end up by failing with version upgrades, to fix this I've introduced a mock to control this value.

### CODE REVIEW

**Comment by vincentkelleher** [comment]
There is an issue with some Github tokenless rate limiting 😅 

image

**Comment by vincentkelleher** [comment]
This is fixed and ready for review 😄

**Comment by vincentkelleher** [comment]
Pull request updated with the latest LinkML updates 😉

**Comment by vincentkelleher** [comment]
@cmungall I noticed that you updated the branch with a merge, I've also rebased it so it is up-to-date 😇

**Review by cmungall — APPROVED** [review]

**Pull request merged**
