### PR TITLE
comment out verbose log info statements that percolate out to model g…

### PR DESCRIPTION
**Pull request by sierra-moxon**
…enerations

### CODE REVIEW

**Comment by cmungall** [comment]
This PR partially mitigates #1689 but we need to figure out what is going on and why these are leaking in the first place!

**Review by cmungall — APPROVED** [review]

**Comment by dalito** [comment]
Which command produced the problem?

From a quick look: I miss at the top of the file on module level a line `logger = logging.getLogger(__name__)`. Then all logging messages should be created using that logger. So it should be `logger.info(...)` not `logging.info(...)`. The latter falls back to using a default logger.

**Comment by pkalita-lbl** [comment]
Maybe close in favor of https://github.com/linkml/linkml/pull/1790?

**Comment by pkalita-lbl** [comment]
Closing now that https://github.com/linkml/linkml/pull/1790 is merged.

**Pull request closed without merging**
