### PR TITLE
Replace metamodel with kitchen sink in script tests

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
Fix: https://github.com/linkml/linkml/issues/1948

Another simple one that looks scarier than it is - replace the metamodel with the kitchen sink model and update the snapshots to match. 

Only editorial choices i made here were to use the `Person` and `Event` classes in place of the `schema_definition` and `element` classes.

To fix before merging:
- [ ] Marked `test_gen_rdf` tests as `xfail` for now because when rdflib tries to parse the JSON-LD string that gets generated, it makes a call to `https://linkml.io/linkml-model/linkml_model/jsonld/tests/kitchen_sink/core.context.jsonld/kitchen_sink/core.context.jsonld` which doesn't exist, and so it 404's and errors. Wasn't sure what to do there, so waiting for guidance.
- [ ] Decide which metamodel tests we want to have! Ideally we would test the correctness of the generators independently, but having some checks that the metamodel is consistent is good for double checking we're not breaking things unexpectedly. Are there any metamodel tests we want to keep from `test_scripts`, keeping in mind that comparing to snapshots is only as good as our snapshots, so it's really a 'test of change' - which again is good in the case of being careful about not changing metamodel accidentally, but might not be necessary for all generators.

Edit: swapping out the metamodel for kitchen sink made `test_meta` in `test_gen_shex` no longer 7 minutes! now completes in ~10 seconds, so removed the `slow` mark! woohoo

Edit2:
Test duration before: [25m](https://github.com/linkml/linkml/actions/runs/8251230764/job/22567793478)
Test duration this PR: [17m](https://github.com/linkml/linkml/actions/runs/8258775723/job/22591596670?pr=1969)
Difference: -8m (32%)

Edit3: tests are failing because of https://github.com/linkml/linkml/issues/1956 not because of this PR

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
with this most recent batch of PRs, we have gone from the test taking an hour to run to <5m

**Comment by cmungall** [comment]
My preferred course:

- merge this PR
- investigate jsonld context oddity independently
- for our "scattergun test" strategy, we proceed more intentionally along the following lines
    - select a fixed set of N blessed models to include (e.g metamodel, biolink)
    - run gen-project over these and use the snapshot strategy to check for changes (ensures broadness), but don't otherwise test anything combinatorial
    - document the SOP. E.g. if I am changing pydanticgen then I expect perhaps a large no of snapshots to change, but that's OK, I do a bit of TestByGuru, but largely trust regenerating snapshots, for any changes to generated pydantic (if other things change I stop and reconsider)
    - we freeze the version of each model, and make sure we expand imports or ensure imports are to a fixed version
    - we periodically update each model (regenerating snapshots)
    - we increase N where it doesn't adversely impact overall runtime of tests

**Comment by sneakers-the-rat** [comment]
Good with that.

> run gen-project over these and use the snapshot strategy to check for changes (ensures broadness), but don't otherwise test anything combinatorial

Another thing we could do when comparing snapshots is to have a multi-modal testing strategy: do a string equality test first which should be very fast. If that fails, then test equality line by line to report diff. Then try doing modality-specific equality test: eg. Graph isomorphism for RDF, etc. If modality specific test fails, fail test, otherwise warn with location of string diff. Try to keep those warnings close to zero/modify the test to exclude mutable substrings like generation date.

Since the snapshot tests are tests of change, and they are all strings (right?) I think we dont need to do expensive equality comparisons. We could even modify the snapshots to be k:v stores with content hashes so we dont even need to do IO for the snapshot, just read and compare the hash.

> we freeze the version of each model, and make sure we expand imports or ensure imports are to a fixed version

I am not sure what u mean by this, could u clarify? In any case yes re: freeze version, and it would be good to have a separate test to check if the snapshot version is the most recent version, right?

> we periodically update each model (regenerating snapshots)

Ya ya re: above, have a cron job that checks for model updates. We'll catch changes to our generated version of model with tests, but we should also get notified when we need to update model because it changes upstream, esp in linkml-runtime and metamodel

> we increase N where it doesn't adversely impact overall runtime of tests

Yes yes, and we can mark all blessed model tests as slow (assuming they are big and complicated like biolink/metamodel) and only run on ci by default. The major low hanging fruit perf barrier that remains is the yuml generator making calls to an external API, but im about to PR a VCR'd version of those tests with frozen network responses so that should be good. 

From there, since the tests are so much lighter, we can think about other strategies for integration tests with eg. Linkml-runtime and if we want to work on splitting out generators (which I would love to do).

One last thought on this which should probs be its own issue: I feel like since metamodel and pythongen are so core to the whole thing, it might be good to, when metamodel -> python models change, we force using those regenerated models in the tests - ie. We monkeypatch those over the models in linkml-runtime. Anyway not for this PR, but wanted to float idea, will raise that (and any other separate issues) after this

**Review by sierra-moxon — APPROVED** [review]
discussed in dev call: we're ok with this, noticed that we move the metamodel out of all testing, which gave us a bit of pause.  But we should target the metamodel as a separate test and since this is a "copy" of the metamodel that isn't necessarily tied to a model release, we aren't worse off from this change.

**Comment by sneakers-the-rat** [comment]
@sierra-moxon metamodel is still tested! all the metamodel tests are just in one test class now: tests/test_base/test_metamodel.py

each are marked as `slow`, but CI runs `--with-slow` :)

**Pull request merged**
