### PR TITLE
Parse enums properly when generating ShEx

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR addresses an issue raised in #1513 where enums were not being parsed and represented properly in the resulting shex generated by the shex generator.

### CODE REVIEW

**Comment by sierra-moxon** [comment]
from the developers call:
we can close this for now, moving forward with (a very similar in scope, approach) PR: https://github.com/linkml/linkml/pull/1517

**Comment by deepakunni3** [comment]
Uh oh. This is not the validator PR. 
This PR is for fixing a bug in ShEx generator.

The one you might want to close is https://github.com/linkml/linkml/pull/1514 :)

**Comment by cmungall** [comment]
@deepakunni3 would you be able to resolve the conflicts and fix the error in the shex test:

```
======================================================================
ERROR: test_biolink_shex (tests.test_biolink_model.test_biolink_model.CurrentBiolinkModelTestCase)
Just Generate the ShEx file untested
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/linkml/linkml/tests/test_biolink_model/test_biolink_model.py", line 198, in test_biolink_shex
    self.single_file_generator("shex", ShExGenerator)
  File "/home/runner/work/linkml/linkml/tests/utils/generatortestcase.py", line 69, in single_file_generator
    self.env.generate_single_file(
  File "/home/runner/work/linkml/linkml/tests/utils/test_environment.py", line 260, in generate_single_file
    actual = generator()
  File "/home/runner/work/linkml/linkml/tests/utils/generatortestcase.py", line 71, in <lambda>
    lambda: gen(yaml_file, **generator_args).serialize(**serialize_args),
  File "/home/runner/work/linkml/linkml/linkml/utils/generator.py", line 303, in serialize
    self.visit_class_slot(cls, self.aliased_slot_name(slot), slot)
  File "/home/runner/work/linkml/linkml/linkml/generators/shexgen.py", line 170, in visit_class_slot
    node_constraint = NodeConstraint(
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/ShExJSG/ShExJ.py", line 494, in __init__
    self.values = values
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/pyjsg/jsglib/jsg_object.py", line 77, in __setattr__
    self[key] = self._jsg_type_for(key, value, vtype)
  File "/home/runner/work/linkml/linkml/.venv/lib/python3.10/site-packages/pyjsg/jsglib/jsg_object.py", line 218, in _jsg_type_for
    raise ValueError(f"Wrong type for {name}: {Logger.json_repr(element)} - expected:"
ValueError: Wrong type for values: [] - expected: typing.Optional[pyjsg.jsglib.jsg_array.values] got list
```

or let us know if you won't have time to handle it and we can have someone else take over!

**Comment by deepakunni3** [comment]
@cmungall Yes, I can take a look at this. Let me get back to you with a fix for the issue

**Review by sierra-moxon — APPROVED** [review]

**Comment by cmungall** [comment]
looks like there are formatting/ruff errors?

**Comment by cmungall** [comment]
we have a conflict...

**Comment by deepakunni3** [comment]
@sujaypatil96 Thanks! I'll take a look and resolve these conflicts :)

**Comment by deepakunni3** [comment]
Given the merge conflicts and the age of this PR, I am going to retire this one and create a new PR.

See https://github.com/linkml/linkml/pull/1824

**Pull request closed without merging**
