### PR TITLE
simplify feature request template

### PR DESCRIPTION
**Pull request by nlharris**
#2265 didn't specifically mention also simplifying the feature request template but I thought we might as well do that as well

### CODE REVIEW

**Review by cmungall — COMMENTED** [review]
actually for this one I think getting a sense of priority is useful? I defer to you and @sierra-moxon.

But definitely not BOTH importance AND timeline. And a qualitiative answer is fine?

**Comment by nlharris** [comment]
how about if we keep "How important is this feature" but delete the timeframe question?

**Comment by cmungall** [comment]
perfect!

**Comment by nlharris** [comment]
Great, can you approve so this can be merged?

**Review by cmungall — APPROVED** [review]

**Pull request merged**
