### PR TITLE
Add any_of implementation to shaclgen.py 

### LINKED ISSUE #1600: Shacl generator does not support keyword "any_of"
**Describe the bug**
Source code to generate Shacl shapes for "any_of" is missing, `s.any_of` is never evaluated, see [shaclgen.py#L80](https://github.com/linkml/linkml/blob/main/linkml/generators/shaclgen.py#L78). 

**To reproduce**
Assume the following linkML yaml file, called any_of.yaml:

```yaml
id: https://w3id.org/linkml/examples/any_of
name: any_of
prefixes:                                  
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
  
classes:
  Test:
    attributes:
      test:
        any_of:
          - range: string
          - range: States
          - range: Test

enums:
  States:
    permissible_values:
      STATE_1:
      STATE_2:
```
`gen-shacl any_of.yaml` results in the follwing shacl file

```
@prefix rdf: &#60;http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: &#60;http://www.w3.org/ns/shacl#> .
@prefix xsd: &#60;http://www.w3.org/2001/XMLSchema#> .

<https://w3id.org/linkml/examples/any_of/:Test> a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:maxCount 1 ;
            sh:order 0 ;
            sh:path <https://w3id.org/linkml/examples/any_of/:test> ] ;
    sh:targetClass <https://w3id.org/linkml/examples/any_of/:Test> .
```

There is not support of keyword `any_of`. Range of attribute `test` is not considered.

**Expected behavior**
Assuming linkml yaml file of above, Shacl shape should look like this

<pre><code>
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://w3id.org/linkml/examples/any_of/:Test> a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:maxCount 1 ;
            <strong>sh:or ( [ sh:datatype xsd:string ] [ sh:in ( "STATE_1" "STATE_2" ) ] [ sh:class <https://w3id.org/linkml/examples/any_of/:Test> ] ) ; </strong>
            sh:order 0 ;
            sh:path <https://w3id.org/linkml/examples/any_of/:test> ] ;
    sh:targetClass <https://w3id.org/linkml/examples/any_of/:Test> .
</pre></code>

**Additional context**
Bugfix is already provided.

### PR DESCRIPTION
**Pull request by anjastrunk**
closes #1600

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
Would you be able to add a test for this?

**Comment by anjastrunk** [comment]
> Would you be able to add a test for this?

Yes, of course.

**Comment by sujaypatil96** [comment]
@anjastrunk would you be able to help resolve the merge conflicts on the shaclgen.py file?

**Comment by djarecka** [comment]
I wanted to say, that I'm already using the branch to generate my shacl, so would be interested in merging this. Can also help if something is needed

**Comment by anjastrunk** [comment]
> @anjastrunk would you be able to help resolve the merge conflicts on the shaclgen.py file?

Yes, but it will take a few days.

**Comment by sujaypatil96** [comment]
@anjastrunk wanted to check if you had any update on resolving the conflicts in this PR?

**Comment by anjastrunk** [comment]
> @anjastrunk wanted to check if you had any update on resolving the conflicts in this PR?

Conflicts are solved. However, tests are sill missing.

**Comment by djarecka** [comment]
when I was adding `any_of` to `json context` I was asked to add a case [here](https://github.com/djarecka/linkml/blob/dd9567de1ed4a809f3d061ab57e41fd261033ea5/tests/test_compliance/test_boolean_slot_compliance.py#L104).  But I just played with it, and it seems to me to that for `shacl` entire turtle sting would have to be added to pass the test, e.g.:
```
@prefix ex: <http://example.org/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:C a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:maxCount 1 ;
            sh:or ( [ sh:class ex:D ] [ sh:datatype xsd:integer ] ) ;
            sh:order 0 ;
            sh:path ex:s1 ] ;
    sh:targetClass ex:C .

ex:D a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:datatype xsd:string ;
            sh:maxCount 1 ;
            sh:order 0 ;
            sh:path ex:s2 ] ;
    sh:targetClass ex:D .
```
Unless there are some options that should be added for `shacl`?

**Comment by anjastrunk** [comment]
> Would you be able to add a test for this?

Unit tests for "any_of" keyword added.

**Comment by anjastrunk** [comment]
@cmungall thanks to @vincentkelleher all ckecks went green an PR is ready to be merged.

**Review by cmungall — APPROVED** [review]

**Pull request merged**
