### PR TITLE
A first stab at a Golang generator

### LINKED ISSUE #1399: Any interest in a Golang generator?
**Is your feature request related to a problem? Please describe.**
As a developer on a KBase-JGI co-development project, I'm working on a data transfer microservice in Go that incorporates some data types from KBase's Credit Engine. The Credit Engine articulates these types in a LinkML schema, and so it would be natural for me to generate Go code using this schema.

**Describe the solution you'd like**
I'm interested in adding a Golang generator to LinkML, and willing to do the work if I can ask some questions related to the generators that may not be handled in [your relevant documentation](https://linkml.io/linkml/howtos/port-linkml.html). I'm sure this effort can be justified in the context of the co-development project, since it's part of a greater interoperability strategy being pursued by KBase and JGI.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)
The number of types I need for this project is small, so I can certainly write the code myself by inspecting the LinkML schema. But as we all know, maintenance is the elephant in the software room, and it would be nice to have a workflow that simplified updates to the KBase Credit Engine schema (and/or updates to LinkML and its schema features).

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months
Again, the LinkML generator is for ease of maintenance, so my need is not urgent. But I do have some time in the short term to throw at this if there's no opposition from the project.

@ialarmedalien

### PR DESCRIPTION
**Pull request by jeff-cohere**
Here's a simple Golang generator created in the style of the Typescript generator. Go is pretty simple compared to most other programming languages, but offers some features like JSON serialization out of the box. I've used this generator to create some data structures that implement @ialarmedalien 's KBase credit metadata schema and am using it already for a project.

The biggest quirk I can think of is that the name of the Go package in the generated code is a lower-cased version of the LinkML schema, truncated at the underscore. This is my quick-n-dirty way of squaring verbose schema names with [Go's package naming guidelines](https://go.dev/blog/package-names). I'd love to hear your thoughts.

Closes #1399

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Also, let me know if I should add some documentation somewhere!

**Comment by cmungall** [comment]
we should have warned you about the overly verbose github actions/test output... let us know if you need help tracking down what is up

**Comment by jeff-cohere** [comment]
A big thanks to @ialarmedalien for letting me know what was causing the failure.

**Review by cmungall — APPROVED** [review]
thanks!

**Pull request merged**
