### PR TITLE
optimize rendering of Applicable classes section on slot documentation pages

### PR DESCRIPTION
**Pull request by sujaypatil96**
Optimize the rendering of Applicable classes section on slot documentation pages.

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
Did you mean to include poetry.lock?

**Comment by sujaypatil96** [comment]
Yup, I did. We need the changes from the latest release of linkml-runtime v1.7.4 for the update in this PR to work.

**Comment by sujaypatil96** [comment]
Thanks for the feedback @cmungall! I updated the PR to include/enforce the dependency requirement in `pyproject.toml`.

**Comment by cmungall** [comment]
can you resolve the conflicts?

**Comment by sujaypatil96** [comment]
Done!

**Review by cmungall — APPROVED** [review]

**Pull request merged**
