### PR TITLE
Generate basic Pydantic model for data arrays

### PR DESCRIPTION
**Pull request by rly**
Stashing our progress in this draft PR.
cc @oruebel @cmungall 

See also https://github.com/linkml/linkml-model/pull/153/

Fix https://github.com/linkml/linkml/issues/1395

### CODE REVIEW

**Comment by rly** [comment]
Note: two lines are commented out in the first new test pending merge of #1431

**Comment by sierra-moxon** [comment]
It looks like in order to install numpy as a dev dependency, poetry is telling me that we need to update our support map to exclude python <=3.8.0.  We do only test 3.8, 3.9, 3.10 at the moment.

**Comment by rly** [comment]
TODO items:
- [ ] consider whether we want to check for consistency of array lengths, e.g., len(x) == values.shape[0]
- [ ] consider whether we want to add support for xarray objects in addition to numpy objects

**Comment by cmungall** [comment]
upstream PR merged, unfortunately a bit of a conflict..

**Comment by rly** [comment]
> upstream PR merged, unfortunately a bit of a conflict..

Thanks. I'll take a look

**Review by cmungall — APPROVED** [review]

**Pull request merged**
