### PR TITLE
Add the "aggregation" UML relationship to mermaid class diagram

### PR DESCRIPTION
**Pull request by sujaypatil96**
Add the [aggregation](https://www.ibm.com/docs/en/rsm/7.5.0?topic=diagrams-aggregation-relationships) UML relationship to the mermaid class diagram rendered on class documentation pages.

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Example of relationship applied to `Person` class in kitchen sink model.

```mermaid
 classDiagram
    class Person
    click Person href "../Person"
      HasAliases <|-- Person
        click HasAliases href "../HasAliases"
      
      Person : addresses
        
          
    
    
    Person --> "*" Address : addresses
    Person o-- Address
    click Address href "../Address"

        
      Person : age_in_years
        
      Person : aliases
        
      Person : has_birth_event
        
          
    
    
    Person --> "0..1" BirthEvent : has_birth_event
    Person o-- BirthEvent
    click BirthEvent href "../BirthEvent"

        
      Person : has_employment_history
        
          
    
    
    Person --> "*" EmploymentEvent : has_employment_history
    Person o-- EmploymentEvent
    click EmploymentEvent href "../EmploymentEvent"

        
      Person : has_familial_relationships
        
          
    
    
    Person --> "*" FamilialRelationship : has_familial_relationships
    Person o-- FamilialRelationship
    click FamilialRelationship href "../FamilialRelationship"

        
      Person : has_medical_history
        
          
    
    
    Person --> "*" MedicalEvent : has_medical_history
    Person o-- MedicalEvent
    click MedicalEvent href "../MedicalEvent"

        
      Person : id
        
      Person : is_living
        
          
    
    
    Person --> "0..1" LifeStatusEnum : is_living
    Person o-- LifeStatusEnum
    click LifeStatusEnum href "../LifeStatusEnum"

        
      Person : name
        
      Person : species_name
        
      Person : stomach_count
        
      
```

**Comment by sujaypatil96** [comment]
I've read multiple definitions of association relationships (composition / aggregation) and according to my understanding of the definition this is how we would represent "aggregation" relationships. For "composition" which is a stronger association relationship, we need a function which computes classes that are related this way (classes that are defined and used only within a given class).

Can you tell me if the above looks good to you @cmungall @sierra-moxon

**Comment by sujaypatil96** [comment]
If it looks right, I'll add tests to test_docgen and we can bring this feature into docgen.

**Comment by cmungall** [comment]
It looks like this is doubling the number of lines in a figure - do we think this is desirable?

**Comment by sujaypatil96** [comment]
To keep the number of lines in a figure the same we could also combine two relationships -- "association" and "aggregation", which technically makes sense because "aggregation" is a type of weak association.

Here is what the generated diagram would look like:

```mermaid
 classDiagram
    class Person
    click Person href "../Person"
      HasAliases <|-- Person
        click HasAliases href "../HasAliases"
      
      Person : addresses
        
          
    
    
    Person o--> "*" Address : addresses
    click Address href "../Address"

        
      Person : age_in_years
        
      Person : aliases
        
      Person : has_birth_event
        
          
    
    
    Person o--> "0..1" BirthEvent : has_birth_event
    click BirthEvent href "../BirthEvent"

        
      Person : has_employment_history
        
          
    
    
    Person o--> "*" EmploymentEvent : has_employment_history
    click EmploymentEvent href "../EmploymentEvent"

        
      Person : has_familial_relationships
        
          
    
    
    Person o--> "*" FamilialRelationship : has_familial_relationships
    click FamilialRelationship href "../FamilialRelationship"

        
      Person : has_medical_history
        
          
    
    
    Person o--> "*" MedicalEvent : has_medical_history
    click MedicalEvent href "../MedicalEvent"

        
      Person : id
        
      Person : is_living
        
          
    
    
    Person o--> "0..1" LifeStatusEnum : is_living
    click LifeStatusEnum href "../LifeStatusEnum"

        
      Person : name
        
      Person : species_name
        
      Person : stomach_count
        
      
```

This is how it is in the yuml generator currently, and adding this in will take us closer to achieving full feature parity with yuml generator.

**Comment by sujaypatil96** [comment]
Refer to `instantiates` to infer aggregation relationships: https://linkml.io/linkml-model/latest/docs/instantiates/

**Pull request closed without merging**
