### PR TITLE
Add enums to JSON schema

### PR DESCRIPTION
**Pull request by gaurav**
This is a first stab at adding enumerations to JSON Schema generation (#201). It uses the `text` field of the [`permissible_values` slot](https://linkml.github.io/linkml-model/docs/permissible_values.html) to build a list of [enumerated values](https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values) in JSON Schema. Enumerations are generated separately in the file and then referenced via an inlined slot.

I'm not very familiar with all the options of [`pv_formula`](https://linkml.github.io/linkml-model/docs/pv_formula.html), so this code only works with the `permissible_values` slot at the moment. Let me know if there are other cases we need to support here, or if this is good enough for now.

One fix I had to make to fix a bug in linkml-runtime is in b616df8: to fix the Python enum generation bug (https://github.com/linkml/linkml/issues/254), I added a workaround in the Python code being generated here. Once this has been fixed in linkml-runtime (presumably in PR https://github.com/linkml/linkml-runtime/pull/17), this workaround -- and the related test files -- can be removed. If that PR isn't very controversial, it might be worth it to wait for that to be incorporated and published, in which case some code can be removed from this PR before merging it.

This PR modifies the kitchen sink tests and some expected Python and JSON Schema files to bring them in line with the code changes made in this PR. It also adds "chardet" as a prerequisite as the tests don't run without them -- I think it's a prerequisite for pyshexc, but not declared as such in its requirements, so we need to install this ourselves.

### CODE REVIEW

**Comment by cmungall** [comment]
do you want help writing the tests @gaurav?

if you want to wait for 
#247
there is a general purpose jsonschema test that operates over the kitchen_sink schema, which is intended to capture all possible linkml constructs

**Comment by gaurav** [comment]
I added some basic tests in 58278d8 -- hopefully that's better than nothing! Let me know what you think.

(I tried to merge PR #247 into this, but I ended up running into a bunch of test errors, so I thought it would be easier to just make an issue-specific test. Feel free to suggest improvements/request that I merge it into #247 anyway.)

**Comment by gaurav** [comment]
Ack, no, the kitchen test is still failing. I've filed that in a separate issue, which might be better tackled by whoever wrote the enumeration Python data class generator: https://github.com/linkml/linkml/issues/254.

**Comment by cmungall** [comment]
Sorry about that! Harold and I merged the kitchen sink tests even though
there was still some issue. We intended to fix after. Let's talk about it
tomorrow

**Comment by hsolbrig** [comment]
@gaurav  -- I'll take a look at this now.   Don't worry about creating a clean test case...

**Comment by cmungall** [comment]
just checking where we are with this...

**Comment by gaurav** [comment]
@cmungall I've got the tests passing, so I think this is now ready for review! I've put in a workaround for https://github.com/linkml/linkml/issues/254 in b616df8, but if we can fix that directly in linkml-runtime (presumably in PR https://github.com/linkml/linkml-runtime/pull/17), we can remove it from this PR. Or we can merge this PR now and remove the workaround later. Either way works for me!

**Review by cmungall — APPROVED** [review]

**Comment by gaurav** [comment]
@cmungall I removed the workaround for linkml/linkml-runtime#17 since that has now been merged into linkml-release in 1d79ec9. I think this PR is ready to be merged now!

**Comment by gaurav** [comment]
@cmungall Let me know if you need anything else from me before merging this in!

**Review by cmungall — APPROVED** [review]

**Pull request merged**
