### PR TITLE
feat: add support for plantuml generated diagrams

### PR DESCRIPTION
**Pull request by Silvanoc**
Adding an alternative UML generator. The advantage of this proposal over the existing one (YUML) is that it enables the usage of a service that can be self-hosted and doesn' have any license fees.

The source code is a modified version of the YUML generator.

### CODE REVIEW

**Comment by dalito** [comment]
Nice! Will it be possible to produce puml-files (or just final images)?

**Comment by Silvanoc** [comment]
> Nice! Will it be possible to produce puml-files (or just final images)?

@dalito Thanks!

I've implemented it the same way as the yUML generator. If you don't pass the option `-d`/`--directory`, then you get the PlantUML code printed out.

**Comment by Silvanoc** [comment]
For backwards compatibility reasons I've kept the `gen-markdown` option `--noyuml`, although IMO it should be rather be called `--nouml` and apply to both PlantUML and yUML.

**Comment by sujaypatil96** [comment]
@Silvanoc: thank you for your work on this! I didn't know about the [plantuml](https://github.com/plantuml/plantuml) project before this, but it looks like another tool with UML diagram generation capabilities. Currently, the de facto tool that we're using within the linkml framework to generate/render UML diagrams is [mermaid](https://mermaid.js.org/). The only kind of diagrams that we are rendering as part of the web documentation generator (gen-doc/docgen.py) at the moment are [class diagrams](https://mermaid.js.org/syntax/classDiagram.html) (granted showing minimal relationship information, simply because we haven't prioritized it enough to improve the level of detail it shows).

I have a couple of questions for you -
1. Does the plantUML generator you wrote show more comprehensive linking and provide more valuable information than the current mermaid diagrams?
2. Why not focus on improving the detail in the mermaid diagrams rather than introducing another UML diagramming tool? Is there something lacking in mermaid that plantUML provides?

There's also an ER diagram generator in the framework: https://github.com/linkml/linkml/blob/main/linkml/generators/erdiagramgen.py

**Comment by sujaypatil96** [comment]
> For backwards compatibility reasons I've kept the gen-markdown option --noyuml, although IMO it should be rather be called --nouml and apply to both PlantUML and yUML.

The `gen-markdown` generator has also been deprecated (it works, but it's not the default markdown documentation generator anymore) in favor of `gen-doc` which uses mermaid (for UML diagramming) and the jinja2 templating language. Apologies the markdown documentation guide hasn't been updated in a while: https://linkml.io/linkml/generators/markdown.html

**Comment by Silvanoc** [comment]
> @Silvanoc: thank you for your work on this! I didn't know about the [plantuml](https://github.com/plantuml/plantuml) project before this, but it looks like another tool with UML diagram generation capabilities. Currently, the de facto tool that we're using within the linkml framework to generate/render UML diagrams is [mermaid](https://mermaid.js.org/). The only kind of diagrams that we are rendering as part of the web documentation generator (gen-doc/docgen.py) at the moment are [class diagrams](https://mermaid.js.org/syntax/classDiagram.html) (granted showing minimal relationship information, simply because we haven't prioritized it enough to improve the level of detail it shows).

I'm aware of it and I'm not trying to provide here a replacement for it, but offering an alternative with some **advantages** when talking about **top-level diagrams for huge schemas**.

> 
> I have a couple of questions for you -
> 
> 1. Does the plantUML generator you wrote show more comprehensive linking and provide more valuable information than the current mermaid diagrams?

They are very similar WRT the diagrams that you can generate and their features. So WRT this question I wouldn't say that PlantUML has any remarkable advantage.

> 2. Why not focus on improving the detail in the mermaid diagrams rather than introducing another UML diagramming tool? Is there something lacking in mermaid that plantUML provides?

The main difference is that Mermaid is client generated on visualization (on the browser) and PlantUML is generating a diagram on build-time.

Build-time diagram generation has a couple of advantages:
- Less client-load
- Possibility to get an image that can be visualized with a different tool with zoom capabilities. That's relevant if you have huge and complex schemas, where the Mermaid approach IMO doesn't scale. If the individual elements are too small, bad luck.
- Easier to diagnose why a diagram is not showing as expected. The hereby contributed code let you generate PlantUML that you can review and use to diagnose issues by simply removing parts and feeding the rest to a PlantUML server.

> 
> There's also an ER diagram generator in the framework: https://github.com/linkml/linkml/blob/main/linkml/generators/erdiagramgen.py

**Comment by Silvanoc** [comment]
> The `gen-markdown` generator has also been deprecated (it works, but it's not the default markdown documentation generator anymore) in favor of `gen-doc` which uses mermaid (for UML diagramming) and the jinja2 templating language. Apologies the markdown documentation guide hasn't been updated in a while: https://linkml.io/linkml/generators/markdown.html

Even better, I can remove the changes to that file from the patch 👍

**Comment by dalito** [comment]
@sujaypatil96 - FYI ,with [sphinxcontrib.plantuml](https://pypi.org/project/sphinxcontrib-plantuml/) the plantuml diagrams can be rendered from *-puml files as svg (or other formats) and embedded in the docs. But there are probably no strong arguments  for swtiching linkml-docs.

However, for users like myself that prefer plantuml this PR would be a nice addition.

**Comment by Silvanoc** [comment]
@sujaypatil96 WRT the deprecation of `gen-markdown` in favor of `gen-doc`, I think that the documentation should be updated accordingly. As of now I only find three references to `gen-doc` in the documentation and they cannot be considered proper documentation:
1. https://linkml.io/linkml/generators/markdown.html#alternatives
2. https://linkml.io/linkml/faq/tools.html#can-i-include-generated-documentation-in-a-sphinx-site
3. https://linkml.io/linkml/faq/tools.html#can-i-customize-the-markdown-generation-for-my-schema-site

Additionally, I'm miserably failing to the the top-level UML with `--include-top-level-diagram --diagram-type uml_class_diagram`. I'm getting the error `NotImplementedError: This is currently handled in the jinja templates`, and I don't know how to tackle it. But that might me only me not capable of getting what the tool is telling me.

**Comment by cmungall** [comment]
@sujaypatil96 can you give an update on @Silvanoc's comments above?

I think the option to have plantuml as an optional output is most welcome

**Comment by sujaypatil96** [comment]
@Silvanoc: yup, sorry the documentation's been so far behind. We've updated the linkml docs to capture the team's current recommendations on markdown documentation generation here: https://linkml.io/linkml/generators/markdown.html

That being said, based on @dalito and @cmungall's suggestions it would definitely be a nice option to have the markdown documentation generator render either Mermaid or plantuml diagrams in the generated web docs. The way you've developed it currently (as a separate module `plantumlgen.py`) is perfect. We can call this generator within docgen.

It would be nice if we could have unit tests for this generator. There's some documentation in our contributor guidelines: https://linkml.io/linkml/contributing/contributing.html#linkml-testing-framework, but I'm happy to work on this with you.

**Comment by Silvanoc** [comment]
> It would be nice if we could have unit tests for this generator. There's some documentation in our contributor guidelines: https://linkml.io/linkml/contributing/contributing.html#linkml-testing-framework, but I'm happy to work on this with you.

I plan to add unit tests. But as of now I have higher prio tasks in an ongoing project.

**Comment by Silvanoc** [comment]
Marked as draft because adding unittests and fixing issues detected adding the tests.

**Comment by Silvanoc** [comment]
> It would be nice if we could have unit tests for this generator. There's some documentation in our contributor guidelines: https://linkml.io/linkml/contributing/contributing.html#linkml-testing-framework, but I'm happy to work on this with you.

@sujaypatil96 now the unit tests are also in place. The GitHub pipelines are failing only due to the flaky codecov.

**Comment by sujaypatil96** [comment]
@Silvanoc: apologies for the late review on this PR, I/the team got caught up with other priorities and this sort of slipped through the cracks. We're bringing it back onto the front burner, and want to get this merged in at the earliest. Thank you for adding tests for your generator.

I cloned your fork of the repo, switched over to the branch where you have the plantUML generator and generated a UML visualization for the kitchen_sink.yaml schema, which is the test schema that most of our generators use. It did a fantastic job of generating a UML diagram. I checked the diagrams generated by both your generator, as well as the existing yUML generator for feature parity and I saw that everything checked out nicely.

The reason why GitHub Actions is complaining right now on this PR is because you have some upstream changes that you need to bring into your fork: https://github.com/Silvanoc/linkml/pull/1, and doing so will get rid of the `ruff` linting error that Actions is complaining about.

**Comment by Silvanoc** [comment]
> @Silvanoc: apologies for the late review on this PR, I/the team got caught up with other priorities and this sort of slipped through the cracks. We're bringing it back onto the front burner, and want to get this merged in at the earliest. Thank you for adding tests for your generator.

No problem, I appreciate very much your effort to process all PRs. It's normal that those that are not in any critical path are left behind for a while.

> The reason why GitHub Actions is complaining right now on this PR is because you have some upstream changes that you need to bring into your fork: [Silvanoc#1](https://github.com/Silvanoc/linkml/pull/1), and doing so will get rid of the `ruff` linting error that Actions is complaining about.

I've noticed that your PR was equivalent to rebasing onto you upstream `main`. Therefore I've simply rebased instead of accepting your PR in order to have a cleaner git history. I don't like PRs to a PR-Branch simply to sync with the target branch. I very much prefer rebasing. I hope it's fine for you.

**Comment by sujaypatil96** [comment]
> @sujaypatil96 I've noticed that your PR was equivalent to rebasing onto you upstream main. Therefore I've simply rebased instead of accepting your PR in order to have a cleaner git history. I don't like PRs to a PR-Branch simply to sync with the target branch. I very much prefer rebasing. I hope it's fine for you.

Great! rebasing works just as well, in fact it's better because it preserves linear git history. Merging your PR in 🚀

**Review by sujaypatil96 — APPROVED** [review]

**Comment by VladimirAlexiev** [comment]
hi @Silvanoc and @sujaypatil96 !
I know a lot about PlantUML, so I can help to improve the look.
Eg https://linkml.io/linkml/generators/plantumlgen.html can be improved if you add this preamble ([like here](https://www.plantuml.com/plantuml/uml/XP5BQnmn3CVlyoc4ZmiRaciF9McxfOSMIdiiOL1ixOwe7wxb2GmXtxsUVJZhPSBEPMJffxyUkfUCAO_ETlANVSI43dmm91JXxhORs11eJjhImIONymIEt1CbwRH54L0_YnsyWfSEolUoPRBc5HGRzG6KvCH-f-1Fed-FBU3HKOE4c2yGt57Flfy8ayme-qmxIekiHD9Cqb-NBQ7WK0-z3gFFrtHPUilFirG1l_EMVcVCespyw9Pxjen2qhHmUtEpUknUJnlxn2aFcsSgnK-k1sCIYTJt3pAiqRRGLtHSrEqlifWvU1aurk36HHicL_WswNDm4VrKtrymer1-guGfCUwepVg6yd0SfAiNNgtN7q6LOUvKCmIKMGSKU9fTGBDlAMkbwfpx53pO9CjmNK9Rn1sSC70vOvgMSvTtLJMsno2ai-YxRLnijgfGzPyrirntBrUsLWiKYNrjCf23wkgLu5Ju0jPKg7gxjhypBExDCabxrdTbtKmTUpYur-ktqnTYBB_kdhmPdVqF)):
```
hide circle
hide empty members
```

**Comment by VladimirAlexiev** [comment]
@Silvanoc Why do you use Kroki and not https://www.plantuml.com/plantuml/ ? Unlike kroki, that one always has the very latest version of plantuml.
```py
kroki_server: Optional[str] = "https://kroki.io"
```

**Comment by VladimirAlexiev** [comment]
>  send a PR with the proposal

https://github.com/linkml/linkml/pull/2060

**Comment by Silvanoc** [comment]
> @Silvanoc Why do you use Kroki and not https://www.plantuml.com/plantuml/ ? Unlike kroki, that one always has the very latest version of plantuml.
> 
> ```python
> kroki_server: Optional[str] = "https://kroki.io"
> ```

In order to support self-hosted diagram generators. That is in fact what we use in our company.
If I'm right, the APIs are slightly different and I didn't want to add support for both.

**Comment by dalito** [comment]
@VladimirAlexiev see also #1956 for plantuml problems/plans.

**Pull request merged**
