### PR TITLE
workaround for clashing markdown file names

### PR DESCRIPTION
**Pull request by sujaypatil96**
Fix for issue #1151

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
This will change all URLs and w3ids for all existing projects. This has to be a non-default option

**Comment by sujaypatil96** [comment]
Not quite sure I understand how it would break existing URLs for projects and w3ids? As long as we regenerate the documentation with `gen-doc` once again, it should be fine?

But yes, the one thing it would change is the structure of the folder where the target documentation pages are output.

**Comment by sujaypatil96** [comment]
Close this PR. See comments on #632 and #1155

**Comment by sujaypatil96** [comment]
Message from @cmungall:

> it’s not a bad idea, but it would have to be opt-in

**Comment by sierra-moxon** [comment]
@sujaypatil96 - I am going to close this PR per the feedback here.  I'll leave the branch there however, in case we can build on the already good start! :)

**Pull request closed without merging**
