### PR TITLE
Add link to video

### PR DESCRIPTION
**Pull request by nlharris**
Hope I got the .rst format right! I wasn't sure where to add this link; if this seems like a bad place, lmk.

The video I linked to is the one that Sierra said "is the best/most comprehensive/longest that is out there." I can also add links to other videos if desired (e.g. ISMB 2024 one?).

### CODE REVIEW

**Comment by nlharris** [comment]
This failed too; not sure why.

**Comment by cmungall** [comment]
I would make an entirely new page that collections links to presentations, tutorials, articles, etc

numpy is a great model for how our documentation should look (aside: would love someone to improve our splash page #1108). 

We should have a page like this:
https://numpy.org/learn/

**Review by cmungall — CHANGES_REQUESTED** [review]
let's add on a new page

**Comment by nlharris** [comment]
I was just going for a "better than nothing" minor upgrade. If you want a page added, I don't think I have enough understanding of the .rst files to do that. If someone else can start the skeleton, I can add to it.

**Comment by cmungall** [comment]
for incremental, add it here https://linkml.io/linkml/examples.html but we will likely want a new "community" page

**Comment by cmungall** [comment]
succeeded by #2264

**Pull request closed without merging**
