### PR TITLE
[pydanticgen] make default for `Optional[<T>]` always be `None`

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
What @daniel-ji was working on over in https://github.com/linkml/linkml/pull/2201 intersected with what i was working on in https://github.com/linkml/linkml/pull/2228. Also related to https://github.com/linkml/linkml/pull/2019#issuecomment-2019224575 and recent problems in https://github.com/linkml/linkml/issues/2219 via the pattern of multivalued optional slots causing problems in the python generator.

to quote that:

> This should generally be true, right? 
>  - if a slot is `required`, i would expect there to be no default or default factory (unless there is an `if_absent` or other precomputed value), and for models to fail validation is no value is passed. 
> - if a slot is not `required`, the type annotation should be wrapped in `Optional[]` and the default should be `None`. 
> 
> [`Optional` is an alias for `Union[X, None]`](https://docs.python.org/3/library/typing.html#typing.Optional), so there should be a three way definitional equality
`required: false === Optional[] === default = None`

previously in 2019 i had changed the test, but only fixed the behavior by accident by breaking all predefined values for class names that change when they are camelcased - my bad. 

when there is no predefined value and a slot isn't required, the template class `PydanticAttribute` handles setting the default in the `Field` to `None`. 

this builds off 2201 so that should be merged first i think

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Comment by glyg** [comment]
Hi,

Yesterday I re-generated my pydantic classes from the linkml schema after not touching it for a few months.

I understand the rationale behind this change, but my code happens to rely a lot on the previous behaviour, as I assumed throughout that my multivalued class attributes were initialised as empty lists I could `append` to. Now I get `object of type None have no append method` errors.


What would be the best strategy for me to restore the `default_factory` behaviour?

I can always do 

```python
if my_obj.my_multivalued_slot is None:
    my_obj.my_multivalued_slot = []
my_class.my_multivalued_slot.append(var)
```

but this has to be done in a lot of places, as I tend to instantiate minimal objects and populate them later.

Thanks for any hint on how to solve that :)


Best
Guillaume

**Comment by sneakers-the-rat** [comment]
probably the easiest thing to do would be to override the `attribute` template so e.g. `{% if multivalued and not required %}default_factory=list{% endif %}`

https://linkml.io/linkml/generators/pydantic.html#cmdoption-gen-pydantic-template-dir

**Comment by glyg** [comment]
Thanks a lot for the super fast answer, and the rest of your worked :)
The fix works

**Comment by cmungall** [comment]
I don't think the template solution is best in the long term. I don't love combinatorial explosion of flags but having some kind of flag here (at the pydanticgen level, potentially later in the schema).

There is a lot of code in the wild that is written to use the generated dataclasses. It would be great if it could just be swapped out without lots of null checks before appending..

**Comment by sneakers-the-rat** [comment]
I'm looking at the linked PR, why is it unclear when the values should exist? I.e. why couldn't the models be initiated so they have a known null state and are then populated by assignment, or have the values computed and passed at instantiation, rather than being appended in a for loop?

**Comment by sierra-moxon** [comment]
https://github.com/linkml/linkml-map/pull/87

**Comment by sneakers-the-rat** [comment]
yes that is the above template workaround, it looks like that was the successor to https://github.com/linkml/linkml-map/pull/86 
i can see why an option might be useful, and that would be relatively straightforward to propagate through the template models. i think some of the awkwardness there could be handled by inverting the order of instantiation -> population to population -> instantiation and making types that handle the list -> dict[name, item] coercion (you'll want to do that with pydantic models anyway, since pydantic validation/coercion doesn't work when you mutate a collection instance's members instead of passing them on instantiation). less boilerplate overall.

for general use i still think the default should be for "no value present" to be distinguishable from "empty collection present," but i don't see a problem with having an option for collapsing them. want me to write that?

**Pull request merged**
