### PR TITLE
changed prefixs in test_issues

### PR DESCRIPTION
**Pull request by krishna-saravan**
#613 issue | changed the issues according to contributing.md guidelines

### CODE REVIEW

**Comment by cmungall** [comment]
Thank you @krishna-saravan!

As you can see the build is failing. However, I think you did the right thing. I think your fix has revealed the fact that we have had a failing test all this time.

Apologies for the fact the github actions output is so hard to read: we have an open issue to clean this up

It looks like this is failing:

test_linkml_test_issue_163.py

In fact this test is for a long-standing issue https://github.com/linkml/linkml/issues/163 (@hsolbrig any chance we can finally fix this?)

I will leave it to @sujaypatil96 to coordinate how to proceed. One path you might want to consider is placing a `@skip` annotation of the failing test, just so we can get this merged (we never merge failing tests). If we do this, then we should add a note in the comments for #163 that we need to unskip the test. However I would not expect someone new to the project to fix 163 as it gets into the guts of linkml a lot!

**Comment by sujaypatil96** [comment]
Thank you for the change @krishna-saravan.

Could you change the files accordingly:

* `tests/test_issues/test_linkml_issue_313.py`
* `tests/test_issues/test_linkml_issue_315.py`
* `tests/test_issues/test_linkml_issue_163.py`

This goes against our guidelines in the CONTRIBUTING.md doc, but for historical reasons and to avoid conflicts with tests coming from biolink, we should do this.

Like @cmungall suggested, you can skip test_linkml_issue_163.py by adding a `@unittest.skip()` construct, similar to this [test](https://github.com/linkml/linkml/blob/main/tests/test_generators/test_sqltransform.py#L25). We can enable it once, issue #163 has been resolved.

**Review by sujaypatil96 — COMMENTED** [review]
Thank you for the change @krishna-saravan.

Could you change the files accordingly:

tests/test_issues/test_linkml_issue_313.py
tests/test_issues/test_linkml_issue_315.py
tests/test_issues/test_linkml_issue_163.py
This goes against our guidelines in the CONTRIBUTING.md doc, but for historical reasons and to avoid conflicts with tests coming from biolink, we should do this.

Like @cmungall suggested, you can skip [test](https://github.com/linkml/linkml/blob/main/tests/test_generators/test_sqltransform.py#L25)_linkml_issue_163.py by adding a @unittest.skip() construct, similar to this test. We can enable it once, issue https://github.com/linkml/linkml/issues/163 has been resolved.

**Comment by cmungall** [comment]
https://github.com/linkml/linkml/runs/5280664896?check_suite_focus=true#step:6:2206

```
  File "/home/runner/work/linkml/linkml/tests/test_issues/test_linkml_issue_163.py", line 43, in IssueRDFNamespaceTestCase
    @unittest.skip()
TypeError: skip() missing 1 required positional argument: 'reason'
```

See https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures

**Pull request merged**
