### PR TITLE
Add documentation on `linkml-ws new`

### PR DESCRIPTION
**Pull request by sujaypatil96**
Add sphinx docs on how to use the LinkML workspace generator command to get setup with a pre defined directory structure for your project.

### CODE REVIEW

**Comment by sujaypatil96** [comment]
PR #764 will need to be reviewed and merged first.

**Review by cmungall — CHANGES_REQUESTED** [review]
This is great, but ws-new isn't a generator see https://linkml.io/linkml/generators/index.html

**Comment by sujaypatil96** [comment]
Ah, right. What section do we want to add the linkml-ws new docs then?

**Comment by cmungall** [comment]
add to howtos

**Pull request merged**
