### PR TITLE
[WIP] Pydanticgen: support polymorphism using type designators

### PR DESCRIPTION
**Pull request by kervel**
This makes the following modifications:
* The type designators are const=True now in pydantic so that pydantic can use them to determine which class needs to be instantiated
* We specify a union of all possible types (using class_descendants) for the range of an slot that refers to a class having a type designator

References:
* https://github.com/pydantic/pydantic/issues/503
* https://github.com/linkml/linkml/issues/1099

Open questions:
* I use two APIs that are slow (i think): the induced slots and the descendants of the class. is this okay ?
* I now only enable polymorphism for things that have a type designator. Actually, in some cases it should be possible to enable polymorphism for things without a type designator (pydantic will simply try all classes and takes the first one that validates). However, i think this is a safe approach for now
* I have no idea (and i would need help) in order to add tests and documentation.
* I think the python dataclasses generator needs a similar modification

### CODE REVIEW

**Comment by sierra-moxon** [comment]
Hi @kervel  - thanks so much for this PR! :)  I see a few open questions on the PR; may I convert this to a "draft" PR while we work through them?

**Comment by kervel** [comment]
yes off course. i'm used to gitlab where when prefixing with WIP its draft automatically, sorry.

**Comment by sierra-moxon** [comment]
Oh that makes sense - I haven't worked much with gitlab :) converting now.

**Comment by kervel** [comment]
thanks. i guess the next step would be getting some feedback/review on this ? is there somebody who could help me out on that ?

**Comment by sierra-moxon** [comment]
Hi @kervel - definitely :) - we are just about into the holidays in the US now, so our replies may be a bit slower than usual.  

Open questions:

```I use two APIs that are slow (i think): the induced slots and the descendants of the class. is this okay ?```

- yep, this is our intent with schemaview, that we use its methods to help traverse the model.  we can work on the speed of these methods in a separate ticket, if they are too slow?

```I now only enable polymorphism for things that have a type designator. Actually, in some cases it should be possible to enable polymorphism for things without a type designator (pydantic will simply try all classes and takes the first one that validates). However, i think this is a safe approach for now```

👍 

```I have no idea (and I would need help) in order to add tests and documentation.```

- actually, we are in the process of refactoring the testing architecture to make it more approachable.  :). Did you happen to find this [document](https://linkml.io/linkml/contributing/contributing.html)?  It has some good details on setting up a new test.  We can also do a meeting to work through this together.  

In fact, we'd love to have you at our LinkML community meeting in the new year, and I'd be happy to add you to our slack and see if we can iterate more quickly there.  Expect an invite shortly! :) 

```I think the python dataclasses generator needs a similar modification.```

- yes - I think #945 will be the grouping ticket for adding this kind of modification to all our generators.

**Comment by kervel** [comment]
Hello!

* About the slow API's: i don't think they are too slow, but every time i generate code for a slot with a class range, i check if that class has an attribute or slot with a type designator. This will make code generation slower even for models that don't have type designators. For me it seems to be unnoticeable, but maybe for big models it might be a problem. I was just checking if this is acceptable or not.

* I am going to read the document you mentioned, and come up with a test

**Comment by kevinschaper** [comment]
Thanks so much for this PR! Thank you especially for catching that the designates_type field wasn't getting populated anymore. 

I wasn't sure about the semantics of `inlined` and `inlined_as_list` when I wrote the logic that you fixed up, and I have to admit that I set both to true in my schemas where I wanted to inline as a list. I think this interpretation makes sense, if inlined isn't set or is false, and inlined_as_list is true, that should be enough to get the inlined_as_list behavior.  

The only thing that I'm not sure about is populating with the `class_uri` rather than `prefix:camelcase(class_def.name)` 

I know that for my own usage, I want a class_curie rather than a class_uri, but I don't have a good argument for why that should stay as the default behavior. What do you think @sierra-moxon @cmungall ?

**Comment by kervel** [comment]
i opted for the full URI because i tought its more logical, since the generated pydantic code doesn't know anything about prefixes, a curie seems to be something more that is valid in a local scope where the prefix definitions are made explicit...

**Comment by sierra-moxon** [comment]
Likely tangential, but I just wanted to give the example here of identifiers.org changing their base URIs from HTTP to HTTPS,  meaning that those using HTTP identifier.org URIs as keys have a conundrum.  Because of all the churn in this (at least in the biological domain), I would be more confident in storing curis as keys in a datastore than URIs.

**Comment by cmungall** [comment]
@kevinschaper 
> I wasn't sure about the semantics of inlined and inlined_as_list when I wrote the logic that you fixed up, and I have to admit that I set both to true in my schemas where I wanted to inline as a list. I think this interpretation makes sense, if inlined isn't set or is false, and inlined_as_list is true, that should be enough to get the inlined_as_list behavior.

See: 

- #1199

Do you think we should also document the intended behavior of code here too: https://linkml.io/linkml/schemas/inlining.html

**Comment by kevinschaper** [comment]
@kervel Here is an example of a standalone issue-specific test for pydanticgen: https://github.com/linkml/linkml/blob/main/tests/test_issues/test_linkml_issue_1094.py

To avoid generating new test artifacts, my approach has been to run a specific test like this locally, but let the broader test suite run in a PR.

**Comment by cmungall** [comment]
@kevinschaper 
> The only thing that I'm not sure about is populating with the class_uri rather than prefix:camelcase(class_def.name)

I updated #945 to state what the defaults should be. This should be driven by the `range` of the slot that is designated to hold the type

**Comment by sierra-moxon** [comment]
Hi @kervel  - can I ask a favor?  Can you change the destination of this PR from `main` to `kerval_pydantic`?  I created this new branch so that @kevinschaper @cmungall and I can round out the tests on this great addition to the project.  I can give you LinkML branch access as well, just to make development easier.

**Comment by kervel** [comment]
I think my explanation of why i think URI's are better suited as type designators than CURIEs was not very clear, so i'm going to try again.

For me the type designator field is actually a way of expressing the is_a relationship in serialisation formats that don't have it out of the box, like json and yaml. I'd say we should strive to encode the type information in the most universal way possible: a json file generated by pydantic code should be interpretable by other code that is not pydantic. And i think this gives some arguments for using the full URIs.

* A CURIE is actually a short hand notation for an URI, but the CURIE in itself lacks the context needed to expand it to a full URI. Typically, the serialisation formats that don't support is_a out of the box also don't support defining prefixes out of the box. So, we have no way to encode what our prefix means, and the type designator fields contain opaque information that is only readable by code that has a built-in list of prefixes.
* Suppose we have two schemas (say A and B) that import a common third schema (C) with a different prefix. If we use URIs then objects of schema C expressed in one schema can be interpreted in the other, otherwise they can't.

Curies could be used as a "fix" for schema's that change their URIs. But i think the use of this fix is limited (only yaml / json could be "fixed" like this, won't help for rdf or json-ld), and it won't help in case other parts of the URI change.

So in my opinion URIs are more suitable than CURIES in this case. However, if the consensus is to use CURIES anyway, in my specific case it would not pose problems, and i can change the PR back to CURIES.

Awaiting your feedback.

**Comment by kervel** [comment]
> Hi @kervel excited to see this WIP PR! I'm wondering if or how this might affect the linkml validator. In other words, would additional work need to be done to the `linkml-validate` command to support validating schemas that use this approach for modeling polymorphism?
> 
> Also tagging @cmungall

Hello,
this PR in itself won't fix the validator yet. for this, changes are needed in the json schema gen and the python dataclasses gen. I have prepared these changes in [another branch](https://github.com/Kapernikov/linkml/tree/polymorphism_dataclasses), will make a separate PR for that, once

**Review by kevinschaper — APPROVED** [review]

**Pull request merged**
