### PR TITLE
Implement equals_string and equals_string_in

### PR DESCRIPTION
**Pull request by anjastrunk**
shacl-gen does not support `equals_string` and `equals_string_in`. As [SHACL](https://www.w3.org/TR/shacl/) does not provide a special node constraint for `equals_string` and `equals_string_in`, I used general constraint [sh:in](https://www.w3.org/TR/shacl/#InConstraintComponent).

### CODE REVIEW

**Review by cmungall — APPROVED** [review]
Ready to review once the format check passes 🙏

**Comment by anjastrunk** [comment]
> Ready to review once the format check passes 🙏

I struggle with format checks. Checks complaining about unsorted imports in file `tests/test_compliance/test_core_compliance.py` I didn't change the file. I already sorted imports with isort, but errors remains. Any hints, how to solve the problem?

**Comment by clange** [comment]
For the record: this work was done during [the 7th Gaia-X Hackathon](https://gitlab.com/gaia-x/gaia-x-community/gx-hackathon/tech-x-2024-and-hackathon-7/-/wikis/Advancing-the-LinkML-based-CI-infrastructure-of-WG-Service-Characteristics) at [Tech-X 2024](https://gaia-x.eu/tech-x-2024/).

**Comment by cmungall** [comment]
@anjastrunk - the conflicts look quite easy to resolve - do you want to try or shall we take it from here?

**Comment by anjastrunk** [comment]
> @anjastrunk - the conflicts look quite easy to resolve - do you want to try or shall we take it from here?

Please take on. I guess, you will be faster and I will not have the time within the next months. I also added unit tests for `equals_string` and `equals_string_in`, which went well but cause other tests to fail. Maybe some of you, who is familiar with your unit test setup, can solve this quickly.

**Comment by vincentkelleher** [comment]
@anjastrunk I've raised a pull request on your repository to propose all the needed test fixes 😉 

https://github.com/anjastrunk/linkml/pull/1

**Comment by cmungall** [comment]
Succeeded by #2150

**Pull request closed without merging**
