### PR TITLE
Add util functions for typescript in generator

### PR DESCRIPTION
**Pull request by amc-corey-cox**
This implements the utility functions in typescript that I mentioned in #1782. This is based on how I use these in a web app I've based on my schema. I'd appreciate any thoughts and feedback on whether I should manage this differently. It's important to remember that typescript compiles out all types during runtime, so types are only checked at compile-time. These helper functions can be used to ensure we conform to the interfaces during runtime.

### CODE REVIEW

**Comment by amc-corey-cox** [comment]
Fixes 1782

**Comment by amc-corey-cox** [comment]
I realized I should probably add a few tests on this... I'll add those after I get some feedback on the approach here and whether this is appropriate generation.

**Comment by amc-corey-cox** [comment]
Okay, I also realized I'm not creating appropriate attributes for when the supplied object doesn't have an attribute. This would require checking the multivalued and type on the slot and creating the appropriate empty object or primitive. I'll add this if we decide to move forward.

Similarly, I think this should be optional and I'll add a flag to add these if desired. I'm currently planning to use --gen-type-utils unless someone tells me a more appropriate flag.

**Comment by amc-corey-cox** [comment]
Okay, the things I mentioned earlier were easier to add than I thought... I'll want this output for my development anyway, even if we don't main-line this. I do think these functions are useful, especially for Typescript. Because Typescript treats types in an unusual way, having utilities to ensure type safety and type-checking is potentially more important than in other scenarios.

**Comment by amc-corey-cox** [comment]
I can pull the slot inheritance into another PR if we want to consider it separately; it was small so I just threw it in.

**Review by cmungall — APPROVED** [review]

**Pull request merged**
