### PR TITLE
Fix xsd:anyURI range in JSON-LD generator

### PR DESCRIPTION
**Pull request by vincentkelleher**
When a JSON-LD context is generated with attributes having `range: uri`, those attributes are converted to default `"@type": "@id"` objects instead of `"@type": "xsd:anyURI"` objects.

In order to be able to use `xsd:anyURI`, I've added the `xsd` context to the default JSON-LD context generator output.

### Example

Let's take the following LinkML ontology.

```yaml
id: https://my-context.com/example#
name: example
prefixes:
  linkml: https://w3id.org/linkml/
  my: https://my-context.com/example#
default_prefix: my
imports:
  - linkml:types
default_range: string

classes:
  Entity:
    description: 'An example entity using xsd:anyURI'
    attributes:
      url:
        title: 'Entity URL'
        description: 'The URL of an endpoint'
        range: uri
```

To be able to use this ontology, the following JSON-LD content can be provided.

```json
{
  "@context": "https://my-context.com/example#",
  "@type": "my:Entity",
  "my:url": {
    "@type": "xsd:anyURI",
    "@value": "https://bakeup.io/terms-and-conditions/"
  }
}
```

### CODE REVIEW

**Comment by cmungall** [comment]
thx! you may need to regenerate snapshots, see https://linkml.io/linkml/contributing/contributing.html

**Comment by vincentkelleher** [comment]
> thx! you may need to regenerate snapshots, see https://linkml.io/linkml/contributing/contributing.html

Hi @cmungall 👋 

I created the pull request a tiny bit too quickly 😬 I'm currently working on updating snapshots and tests so I converted this to a draft and I will change it when I'm finished.

**Comment by vincentkelleher** [comment]
@cmungall I've fixed all the failing tests and checked that the changes are in control, everything seems fine so this can now be reviewed 😉

**Review by cmungall — APPROVED** [review]

**Comment by vincentkelleher** [comment]
Thank you for the quick review and merge @cmungall 🙏

**Pull request merged**
